### ISSUE TITLE
Wishlist: Full Whitelist in SQLBlackWhiteList.pm

### ISSUE THREAD

**Issue by mmgomess** [mailwatch/MailWatch#709]
Is it possible for the Mailwatch whitelist works like a full bypass? 
Spam, content and virus whitelist.

I know I can solve this with a "Spam Scan" ruleset in Mailscanner, but I would like to have this option in Mailwatch

Marcelo Gomes

**Comment by asuweb** [comment]
Assuming what you want is to whitelist an entire domain (so that any emails where the "From" contains the domain), then yes it can.

Simply put the domain in the from box (no @ or anything) and leave the to blank, select whitelist and create. 

You could do the reverse to whitelist anything sent to a domain, by leaving the from field blank, and only filling in the portion after that @

![image](https://cloud.githubusercontent.com/assets/13250955/25988079/8c1ac562-36ee-11e7-95cb-42fa3047a2cb.png)

**Comment by asuweb** [comment]
This won't bypass the virus scanner, but I can't see why you'd want to.

**Comment by Skywalker-11** [comment]
It is not possible to disable the virus scanning with MailWatch but you can do it in MailScanner by using a rule for `Virus Scanning` in the MailScanner config
[https://www.mailscanner.info/MailScanner.conf.index.html#Virus%20Scanning](https://www.mailscanner.info/MailScanner.conf.index.html#Virus%20Scanning)

**Comment by mmgomess** [comment]
OK. Thank you.

Mareclo Gomes.

2017-05-12 5:17 GMT-03:00 Michael Pietsch <notifications@github.com>:
