### ISSUE TITLE
Static pages terminate the session even with self-refresh active

### ISSUE THREAD

**Issue by Daniel-Beardsmore** [mailwatch/MailWatch#783]
As noted in issue #730, self-refresh pages prevent session timeouts. However, if you have a self-refresh page _and_ a static page open in separate tabs, the static page forcibly closes the session that the self-refresh page is trying to use.

1. Log in; this will show the Recent Messages page that will automatically refresh
2. Open any static page (e.g. Black and White Lists) in a new tab
3. Wait ten minutes — _both_ tabs will be logged out, with _only_ the static page offering an explanation (since the self-refreshing page will find itself logged out unexpectedly)

Normally, sessions on websites are closed at the server side, but here it seems that the pages themselves send the session close message. In order for this implementation to make any sense, such pages would need to request a server close via AJAX, to which the server would respond either with true: session has been closed at the server end, so you can tell the user, or with false: session is actually in use, so the request to have it cancelled was rejected.

This is EFA 3.0.2.2's supplied copy of MailWatch v1.2.3-dev. Confirmed in both Firefox and Opera.

Per issue #730, no response was given to the issue of changing the timeout; this surely should be a setting in a new file etc/mailwatch.conf along with other settings such as the the identity of the server in case you have more than one Mailwatch server.

Now, a ten minute timeout isn't necessarily a problem. However, the security enhancement argument behind the enforced logouts makes no sense. If leaving the site unattended is a security risk, why can it be left on self-refresh at all? Per issue #730, self-refresh is _supposed_ to leave your session open, which means that there's a clear conflict here that has led to confusing behaviour. Either self-refresh holding open the session should be forbidden outright (for the same reason that leaving as static page open is prohibited), or static pages should not interfere with the intended behaviour of self-refresh holding the session open for you.

Otherwise, a timeout longer than 10 minutes should be cleanly configurable in conf file.

Worse, you can get "Error: unable to validate security token" trying to log back in, and none of the login pages contain the URL of the page that you were on, to return to it.

**Comment by stefaweb** [comment]
> If leaving the site unattended is a security risk, why can it be left on self-refresh at all?

Hello!
I do not agree with that. No security risk here.
The status page is a visualization page. Nothing can be changed from this page. If you click on something on the status page, you will go directly on the login page.

**Comment by asuweb** [comment]
No, if the status page is left open the session is kept alive, and you can access any page you want.

**Comment by stefaweb** [comment]
@asuweb : This have changed? If yes, not good. 
In the first version, it was working as I previously described.

**Comment by asuweb** [comment]
@stefaweb - it has never worked like that - at least not on any version I'm running.  If you leave the status page open, it auto-refreshes, which keeps the sessions alive (in fact it actually recreates it I think).  

Which means that you can then navigate to any page you like, because the session is still valid.  I haven't logged in for about 4 days, as I keep the status page open, and then view other pages are required.

**Comment by stefaweb** [comment]
In my memory it worked like this before we put the token system in place. Maybe I'm wrong as you wrote. My wish at the time was that the autorefresh without disconnection is only functional on the status page and queue page.
Currently, the system suits me but on the other hand if we can connect it elsewhere, it is not very secure.

**Comment by Daniel-Beardsmore** [comment]
I'm confused by comments suggesting that somehow the status page does, should, or could be assumed to run in a different session to all the other pages. I don't know of any sites or software that has such split sessions. It's not impossible (logging in could create two sessions, one for safe pages and one for unsafe pages) but that's just asking for confusion, and now we have exactly that confusion.

The recently-introduced timeout is short enough as to cause serious inconvenience; when investigating some issue with a number of tabs open on listings and messages, all these tabs will readily self-destruct, wiping out your entire view on the situation at hand. It's a huge backwards step for usability.

I'd personally just increase the timeout, but there seems to be no setting for this. The self-refresh page always held the session open in the past, but now each individual page will close the session regardless.

**Comment by stefaweb** [comment]
May be adding a timeout constant in the config file should not be very complicated. 
I agree that sometime the 10 minutes timeout can be a problem. I had this problem during a phone call with a customer last week. We talk of a problem with a regular mail tagged as spam. I was on detail page and lost the stuff due to the timeout during the phone call.

**Comment by asuweb** [comment]
@Daniel-Beardsmore - I agree, split sessions are the not the answer, and we don't want to go down that road.

The main issue as far as I can tell is when users are using multiple tabs / windows, and sessions aren't working correctly, due to the static pages destroying the session on expiry.  This is less than optimal, as you've discovered.

The most robust solution I can think of would be to handle login timeouts via the database rather than sessions.  In this way, it will be consistent across the board, and we then not relying on browser differences, and it will also cater for load balanced systems and the likes. 

We could simply set a login_expiry field in the users table.  This would be populated with the current time + a admin configurable timeout value (10 mins, 30 mins etc).  On each page access this value is checked against the current time, and if current time exceeds login_expiry, user needs to login.

Session could be used to destroy the session on browser close as is normal.

**Comment by shawniverson** [comment]
Four different distinct issues here, I think...

1) Addressing the issue of multiple tabs.  This will be a major rewrite of token handling, as two tabs open on the same page will trample the existing session and form tokens, causing the first tab to throw an invalid security token message.  This is easy to observe by opening the same form in two tabs and trying to complete the form in the first tab.  Token handling will need extended to handle multiple tabs on same and different areas within a session.  Tokens will need to be tab aware.

2) I agree the security argument for timeouts is invalid since you can simply leave open a status/queue page, and the timeout becomes irrelevant everywhere.  Why even have a timeout in this case? A simple solution might be to create a new user type, a monitor only user, that only has access to these refresh pages and nothing else for dashboard purposes.  All other user types would timeout normally, including refreshed pages.  Or, given the current situation, timeout just needs eliminated in whole or in part.  Session rotation could be kept to prevent session hijacking over an extended time period.

3) I am in favor of a configurable timeout in the MailWatch configuration.  Everybody's security requirements are different, I think.  This is a simple fix.

4) I like the db approach of @asuweb.  This would enhance the entire system and provide useful data to the admin.

Thoughts?  I can take whatever direction the MailWatch team decides.

**Comment by Daniel-Beardsmore** [comment]
Normally when you log in somewhere, you're given a session ID. Ideally this goes in a cookie, but some sites put the session ID into URLs, making the URLs messy and cumbersome and risking session leaks if you copy/paste a public URL (e.g. to a product listing or forum topic) into a message to someone, and where this URL to a public resource nonetheless contains your session ID. (This blunder is partially mitigated by tying a session to an IP address, so long as everyone is seen to come from a distinct IP address.)

Session tokens should just live in a cookie, be neither seen not heard, and never cause an issue. If tabs break session tokens, then the session token implementation is wrong.

Forms on the other hand, will break if they're relying on session state that is not tab-aware, particularly wizards. I've always used hidden form fields to localise everything to the form, so that even multiple instances of the same wizard don't conflict. This would cause trouble if you wanted file upload form fields within the middle of a wizard though!

I've not seen anything so far in MailWatch that seems to be tab-specific — I've not seen any wizards and I've never seen anything break from multiple tab usage. Multiple MailWatch tabs have never given me any trouble until now, so I can't envisage any situation where you'd have a serious conflict between forms and tabs.  Those with more experience than I have may be able to explain the technicalities behind this.

**Comment by asuweb** [comment]
**To address point 1** - it's perfectly acceptable to use a **single token per session**, instead of generating one per request.  This would instantly solve the tab issue.  Additionally, to protect against man-in-the-middle attacks, we should be enforcing SSL (if we're actually addressing security)

In today's world, SSL encryption is cost neutral, and simple to set up.  Using LetsEncrypt or the likes (if you don't have a need or wish for paid SSL certificates) is perfectly acceptable, and can be fully automated very easily. I would suggest it should it be encouraged / enforced.  If we're going to the trouble of CSRF to enhance security, it seems illogical to not require SSL as well.

**Point 2** - I mentioned months ago that perhaps having a configurable list of user who are allowed to keep sessions open would be the simplest way to solve this.  That way the sys-admin can decide which user he/she trusts / has an operation requirement to keep the status pages open, and thus the session alive. In reality, end users aren't going to be watching the status page (or if they are they really need to get out more).  Really, only NOC's or sys-admins are going to want / need this feature.  Perhaps an even simpler approach is to only allow **admins** and **domain-admins** to keep alive?

**Point 3** - this seems like an obvious enhancement, and can be done quickly.

**Point 4** - Obviously I'm in favour

**Comment by asuweb** [comment]
The other option to multi-tab issue would be to store an array of valid tokens, and expire them on session expire or when used.  However, a per session token would still be simpler to implement, and there is little if any advantage by generating tokens per request.

**Comment by shawniverson** [comment]
In response to @asuweb ...

Point 1:  That would work, and I would be fine with it, unless anyone sees any caveats.  Definitely a much simpler approach.  

Point 2:  I'm in favor of this.  Why not just exempt admins/domain-admins from timeouts altogether and just use it for regular users?  They're going to likely have the status page open anyway, so what's the point, except maybe just session rotation?  The timeout logic could then be simplified and wouldn't have to have any refreshing logic.

Point 3 and 4: yes and yes.

**Comment by asuweb** [comment]
@shawniverson - it's acceptable to OSWAP so it's fine with me :)

**Comment by asuweb** [comment]
And yes, I agree with point 2 - I suppose the only advantage of keeping the timeout is to avoid mistakenly leaving it open.  If you have to be on the status page / queue monitor, then that's a deliberate action to take to keep the session open.

**Comment by shawniverson** [comment]
I see a fork in the road....

Not necessarily....what if the status page is mistakenly left open?  Let's say you get pulled to another issue and leave your area?  That's essentially equivalent to having any other page in MailWatch open, whether intentionally or accidentally, since you can just switch to them.  I just think unless we take issue with this possibility, the timeouts are moot and just an interference.  In fact, the more I think about it, just timing out users isn't really useful either if admins aren't also being timed out.  Your risk is much greater with admins, not users.  If this is still an issue, we need to address it fully, perhaps with a monitor only user, and enforce timeout consistently across the board for all admins and users.

To timeout or not to timeout, that is the question.

The basic requirement is to keep MailWatch safe from remote exploit.  Does timing out sessions really fit in this requirement, or can simple session rotation be sufficient? Physical security, well, perhaps that is on the individual admins and organizations.

@endelwar what are your thoughts?

**Comment by asuweb** [comment]
I don't have an issue with getting rid of the timeouts, or possibly a better approach is to give sys-admins the ability to disable them in the config if they want to (after all, no 2 systems / setups / user base are the same)

They were introduced I believe as part of the OSWAP recommendations as far as I recall.

**Comment by stefaweb** [comment]
> a monitor only user
Good idea.
But if this solution is implemented, it should go to login page if we click somewhere in status or queue pages. After, we log with a regular user and we should go where we was trying to go.
For timeout, a constant in config is ok for me.

**Comment by shawniverson** [comment]
Depending on whether or not we keep the timeouts around, we can then decide our next moves.  If it is configurable, then I think timeouts need to be consistent across the board, otherwise it just doesn't make sense to even have timeouts.  It's like building a wall and leaving a wide open hole in the middle.  In the spirit of open source, I think it should be configurable, just like the many other security related options already in MailWatch.

**Comment by pdwalker** [comment]
From an admin point of view, having a session timeout is not really a problem if it is configurable.  If I set it to an hour and I'm away from my desk, my screen will automatically lock, and I have no issues with logging in again after such an extended absence.  Keep it simple and consistent across the board - from 0 seconds (no timeout) to XXXX seconds (where XXXX seconds is a sufficiently large value to make even the most absent administrator happy)

Handling multiple tabs correctly is probably more important to get right.  The current system, while not technically broken, is really not good from a usability point of view.  Who here doesn't use multiple tabs when managing things in their browser?

In my opinion only, of course.

Thanks for all your hard work Gentlemen.

**Comment by shawniverson** [comment]
Anyone see any problems doing this approach?  Basically boil down to two things....

1) Simplified, configurable session timeout using the database approach.

2) Simplified, single session token per session instead of per page/request.

**Comment by asuweb** [comment]
I'm happy with that.  It'll be easier to manage / maintain and will fix all of the above issues

**Comment by Daniel-Beardsmore** [comment]
My feeling is that it would be best to implement the proposed changes, since that would return the software to its expected behaviour.

The more interesting features such as a read-only view of the queues or two-level/dual sessions deserves its own issue(s) as that represents a deviation from the historical behaviour, and the current semi-split behaviour is unintentional.

**Comment by endelwar** [comment]
> @endelwar what are your thoughts?

sorry for the delay, it was a full week.

I was byte by the multiple tabs issue myself too, so I fully agree to modify actual behavior to return to an meaningful user experience.

I agree with the implementation of the 2 points @shawniverson pointed out up there, this will solve the bigger problems that we are seeing.

**Comment by shawniverson** [comment]
I'll get to work on this.

**Comment by shawniverson** [comment]
Working on #2....it appears that the token is already per session, not per page, so that is not the real issue.  It is only generated during login, so...the real issue is the CSRF formtoken, which needs localized to each form instance.

**Comment by endelwar** [comment]
> It is only generated during login, so...the real issue is the CSRF formtoken, which needs localized to each form instance

It must be renewed of any new form displayed even on different tabs, or it has no reason to exists: the problem here is that we have a search form on top left on **every page** so the CSRF token is always renewed.

The only solutions that I can see for now is to remove the search form (boooh!) or remove the token from it (boooh again!)

**Comment by shawniverson** [comment]
@endelwar Take a look at PR #789 for my proposed solution.

**Comment by endelwar** [comment]
I've thought about this and did some research on the matter: owasp and security people recommend to regenerate token when the user changes his/her privileges (unauth on login page -> logged id -> promoted to admin and viceversa), so a timer for form token is too much, generating the form token on login and reusing it on the same session is ok from a security point of view, we just ned to regenerate on session timeout and privilege changes.

**Comment by shawniverson** [comment]
That sounds much simpler.  The articles I read emphasized single use to
prevent CSRF replay attacks.  If that is not an issue, then I can certainly
go this new direction.

**Comment by endelwar** [comment]
Using a refreshed token in every new form displayed doesn't improve the security of the web app, it only makes more difficult to exploit an eventual XSS attack vector already present in code: if this breach exists an attacker can get the refresh token anyway, it just take some more js code...
I'm not saying that single token generation is equal to token refresh, but on the practical code exploitation it's on the same level of difficulty to bypass, and gives our users a worse experience.

**Comment by shawniverson** [comment]
This makes sense.  PR submitted.  This actually revealed a security issue.  We had no privilege check occurring anywhere, so a privilege change could mean that a former admin (as of the change and still logged in) could continue to make changes!  We might want to take a closer look at this.  Although I added it to the forms, are there any other places that need to perform a privilege change check, I wonder?

**Comment by endelwar** [comment]
The privilege change occur in 2 places:
- login form: user change from "guest" to logged in user
- user manage page: an user can be given more power (promoted from user to domain admin or admin) or less (demoted from admin/domain admin to domain admin/user)

I can't think of other places where these privileges change.

We must find a good way to kill logged in user session:
- if we move sessions to database as already discussed it's a simple delete query on user session
- without session table we should check on every session_start that the `$_SESSION['user_type']` equals the one on user table, if it differ we destroy the active session and user is logged out

**Comment by asuweb** [comment]
> user manage page: an user can be given more power (promoted from user to domain admin or admin) or less (demoted from admin/domain admin to domain admin/user)

This could be handled by destroying the session once the user type has been updated in the users table or as suggested by @endelwar.

If we move session to the database, it will give more power to the admins to be able to "kick" a user out if they want.  It also allows admins to check who is logged in, and potentially when they last logged in etc.

**Comment by shawniverson** [comment]
Then although I can do a privilege check in the form token area, it makes more sense to take a broader approach.  If we invalidate the user on privilege change, then that part of the code in the form token becomes moot.  So, what I am going to do is update the PR to drop the privilege check (for the moment) since it won't be implemented there and shift it to the next PR that will address the sessions themselves.

**Comment by shawniverson** [comment]
Ready to close, all issues here should be resolved now.

**Comment by stefaweb** [comment]
Works fine for me.
Stay on status.php, refresh well, and go to login page if we click somewhere.
Stay on the page and go to login page if we click somewhere for others pages.

**Comment by stefaweb** [comment]
> Stay on status.php, refresh well, and go to login page if we click somewhere.

Error go to login page automatically after session expiry.  😞

**Comment by Daniel-Beardsmore** [comment]
Default timeout behaves as it should, and custom timeout also behaves as it should. The basic problem of all your static pages getting replaced with logon pages is gone.

The one thing I do need to check when I get chance, is precisely what actions constitute holding the session open, and whether this works correctly now, as it sounds like the self-refresh has some way of indicating not to hold the session open.

**Comment by Daniel-Beardsmore** [comment]
Something isn't right. Example 1:

Tab 1: status page, self-refreshing
Tab 2: Tools and Links

Manually refresh the Tools and Links page. Session expires in spite of user activity.

Example 2:

Tab 1: status page, self-refreshing
Tab 2: Search and Reports

Repeatedly add and remove a filter criteria. Session expires in spite of obvious user activity.

Conclusion: Either the site is unable to detect the user at all (which is why self-refresh pages don't mark you as being present), or the site has special logic to distinguish user activity and this logic is not functioning correctly.

**Comment by shawniverson** [comment]
Testing on my instance...

**Comment by shawniverson** [comment]
Issue found, preparing PR....a type mismatch

**Comment by stefaweb** [comment]
No way to have no disconnect for auto refresh pages as status.php and mailq.php as in the previous version?

**Comment by shawniverson** [comment]
@stefaweb That is equivalent to having a user with no timeout.  So, simply set the user's timeout to 0 that will be on indefinitely.

**Comment by stefaweb** [comment]
Thanks @shawniverson. It works fine with 0 in Edit User.

May be, it would be nice to enlarge the box. Big numbers don't fit.

![capture d ecran 2017-05-25 a 17 38 45](https://cloud.githubusercontent.com/assets/12907102/26457677/574beb08-4171-11e7-89f5-b80360662a7c.png)

**Comment by stefaweb** [comment]
Questions:

I open on two computers (A & B) a MailWatch session with the same user.

I close the session on computer A.

At session expiry, the session on computer B is closed too (quit status.php and go to login.php).

Normal?

**Comment by shawniverson** [comment]
@stefaweb Yes, that would be normal behavior, since the session database is per user.

**Comment by stefaweb** [comment]
One more.

I'm connected as admin user "adminuser". When I go to user_manager.php, I see this:

![capture d ecran 2017-05-26 a 08 54 37](https://cloud.githubusercontent.com/assets/12907102/26484257/57d5a160-41f1-11e7-931c-e59ee5f415de.png)

Normal to have "Unknown" instead of Yes?

**Comment by shawniverson** [comment]
That's because this account has no timeout set.  Without a timeout, we can't determine whether a user is logged in with the database, since it never expires and is set to 0.

**Comment by Daniel-Beardsmore** [comment]
They're still physically logged in. If I have a session timeout of 60 minutes, and after five minutes I restart the browser, I'm still technically logged in even if my browser has forgotten the session cookie. Having no timeout is not really any different: you've logged in, and not yet logged out, so the answer is "Yes". Since HTTP is stateless, you can't ever tell if the user still has _access_ to their session; you can only know for certain that they have a valid session that they could use if they choose to. "Unknown" just looks like the software is broken and confused. Whether a user is _actively_ utilising their logon session is another matter, as is the time elapsed since logon, since for all practical purposes there's no difference between 0 and INT_MAX here.

**Comment by shawniverson** [comment]
@Daniel-Beardsmore That makes sense, I was focused status on the logon_expiry when I wrote the PR.  So, in the case of no timeout, the answer would be yes instead of unknown, unless the user explicitly or is forced to logout.  I'll prepare a PR.

**Comment by stefaweb** [comment]
Yes 😀

If you have time. Seems better to have "User timeout" below "User type".

![capture d ecran 2017-05-26 a 13 48 15](https://cloud.githubusercontent.com/assets/12907102/26493508/3dd9418a-421a-11e7-9c73-55b617a5c621.png)

**Comment by Skywalker-11** [comment]
I'm not sure if it can be a problem but in case someone is logged in on two computers and on one of them he is active (no timeout) the same goes for the other computer which also will not time out.

**Comment by shawniverson** [comment]
@Skywalker-11 That is true, however, session cookies are still in play, meaning you'll need to log in anywhere a session cookie isn't already present.  I don't think that will be an issue.  I do however, consider logout on a second computer logging out both a bit of a quirk, but I'll leave it up to everyone whether we need to enhance that aspect of it in some fashion.

**Comment by endelwar** [comment]
The world is a beautiful place to live because you will always find 2 people with different views: if you set too strict (but safe) parameters (p.e.: on session timeout) someone will be in need of more freedom, if you give all the freedom of the world (p.e.: set your preferred session timeout in db) someone will say "don't make me think, this is too much for me".
I think that the only solution is to document this cases, explaining the security risk and recommend a safe default.

**Comment by endelwar** [comment]
Documented here http://docs.mailwatch.org/install/optional-setup.html#session-configuration
